server:
  port: 8181

spring:
  application:
    name: hystrix-dashboard

  cloud:
    config:
      enabled: true
      uri: http://localhost:9898

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"